language: r

sudo: required

warnings_are_errors: false

r_binary_packages:
 - testthat
 - runjags

r_github_packages:
 - drackham/dcmdata

r_packages:
 - rstan

# NOT_CRAN and options in .Rprofile are workarounds for "cyclic dependency check" error
# see https://github.com/travis-ci/travis-ci/issues/4125
# Using clang instead of gcc because rstan won't compile on gcc on travis
env:
  global:
    - NOT_CRAN=true CXXFLAGS=-O2 CXX_OLEVEL=2 RCPP_VER=cran CXX=clang++ CPP=clang CC=clang

before_install:
 - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
 - mkdir -p ~/.R
 - echo 'CXXFLAGS=-O2' > ~/.R/Makevars
 - echo 'CC=clang' >> ~/.R/Makevars
 - echo 'CPP=clang' >> ~/.R/Makevars
 - echo 'CXX=clang++' >> ~/.R/Makevars
