# .travis.yml for R CDASimStudies

language: r

# sudo is needed for R on travis-CI. See http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required

warnings_are_errors: false
sudo: required

r_binary_packages:
  - testthat
  - runjags
  - parallel

r_packages:
  -rstan

# Using clang instead of gcc because rstan won't compile on gcc on travis
env:
  global:
    - NOT_CRAN=true CXXFLAGS=-O2 CXX_OLEVEL=2 RCPP_VER=cran CXX=clang++ CPP=clang CC=clang
before_install:
 - echo "options(repos = 'https://cran.r-project.org')" > ~/.Rprofile
 - mkdir -p ~/.R
 - echo 'CXXFLAGS=-O2' > ~/.R/Makevars
 - echo 'CC=clang' >> ~/.R/Makevars
 - echo 'CPP=clang' >> ~/.R/Makevars
 - echo 'CXX=clang++' >> ~/.R/Makevars

notifications:
  email:
  - ddrackham@gmail.com
